-- ============================================================================
-- Rollback for migration 0014 — Tenant Row-Level Security (Task #150)
-- ============================================================================
-- Reverses migrations/0014_tenant_rls.sql in strict reverse-dependency order:
--   1. DROP every policy (they depend on the helper functions)
--   2. DISABLE + NO FORCE RLS on every table
--   3. REVOKE all grants from citefi_tenant
--   4. DROP the SECURITY DEFINER helper functions
--   5. DROP the citefi_rls schema
--   6. DROP the citefi_tenant role (after grants/ownership removed)
--
-- FULLY IDEMPOTENT: every statement uses IF EXISTS / DO-guards, safe to re-run.
-- ============================================================================

BEGIN;

REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public FROM citefi_tenant;
DROP TRIGGER IF EXISTS guard_client_viewer_article_update ON "articles";

-- ---------------------------------------------------------------------------
-- 1. Drop policies (reverse of creation)
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS rls_articles_owner_sel ON "articles";
DROP POLICY IF EXISTS rls_articles_owner_ins ON "articles";
DROP POLICY IF EXISTS rls_articles_owner_upd ON "articles";
DROP POLICY IF EXISTS rls_articles_owner_del ON "articles";
DROP POLICY IF EXISTS rls_articles_viewer_sel ON "articles";
DROP POLICY IF EXISTS rls_articles_viewer_upd ON "articles";
DROP POLICY IF EXISTS rls_activity_logs_sel ON "activity_logs";
DROP POLICY IF EXISTS rls_activity_logs_ins ON "activity_logs";
DROP POLICY IF EXISTS rls_users_sel ON "users";
DROP POLICY IF EXISTS rls_users_upd ON "users";
DROP POLICY IF EXISTS rls_teams_sel ON "teams";
DROP POLICY IF EXISTS rls_teams_upd ON "teams";
DROP POLICY IF EXISTS rls_credit_menu_overrides_sel ON "credit_menu_overrides";
DROP POLICY IF EXISTS rls_credit_menu_overrides_ins ON "credit_menu_overrides";
DROP POLICY IF EXISTS rls_credit_menu_overrides_upd ON "credit_menu_overrides";
DROP POLICY IF EXISTS rls_credit_menu_overrides_del ON "credit_menu_overrides";
DROP POLICY IF EXISTS rls_daily_brief_preferences_sel ON "daily_brief_preferences";
DROP POLICY IF EXISTS rls_daily_brief_preferences_ins ON "daily_brief_preferences";
DROP POLICY IF EXISTS rls_daily_brief_preferences_upd ON "daily_brief_preferences";
DROP POLICY IF EXISTS rls_daily_brief_preferences_del ON "daily_brief_preferences";
DROP POLICY IF EXISTS rls_notifications_sel ON "notifications";
DROP POLICY IF EXISTS rls_notifications_ins ON "notifications";
DROP POLICY IF EXISTS rls_notifications_upd ON "notifications";
DROP POLICY IF EXISTS rls_notifications_del ON "notifications";
DROP POLICY IF EXISTS rls_user_invites_sel ON "user_invites";
DROP POLICY IF EXISTS rls_user_invites_ins ON "user_invites";
DROP POLICY IF EXISTS rls_user_invites_upd ON "user_invites";
DROP POLICY IF EXISTS rls_user_invites_del ON "user_invites";
DROP POLICY IF EXISTS rls_team_members_sel ON "team_members";
DROP POLICY IF EXISTS rls_team_members_ins ON "team_members";
DROP POLICY IF EXISTS rls_team_members_upd ON "team_members";
DROP POLICY IF EXISTS rls_team_members_del ON "team_members";
DROP POLICY IF EXISTS rls_locales_sel ON "locales";
DROP POLICY IF EXISTS rls_local_authority_signals_sel ON "local_authority_signals";
DROP POLICY IF EXISTS rls_journey_templates_sel ON "journey_templates";
DROP POLICY IF EXISTS rls_maintenance_flags_sel ON "maintenance_flags";
DROP POLICY IF EXISTS rls_sessions_sel ON "sessions";
DROP POLICY IF EXISTS rls_sessions_ins ON "sessions";
DROP POLICY IF EXISTS rls_sessions_upd ON "sessions";
DROP POLICY IF EXISTS rls_sessions_del ON "sessions";
DROP POLICY IF EXISTS rls_totp_secrets_sel ON "totp_secrets";
DROP POLICY IF EXISTS rls_totp_secrets_ins ON "totp_secrets";
DROP POLICY IF EXISTS rls_totp_secrets_upd ON "totp_secrets";
DROP POLICY IF EXISTS rls_totp_secrets_del ON "totp_secrets";
DROP POLICY IF EXISTS rls_email_verification_codes_sel ON "email_verification_codes";
DROP POLICY IF EXISTS rls_email_verification_codes_ins ON "email_verification_codes";
DROP POLICY IF EXISTS rls_email_verification_codes_upd ON "email_verification_codes";
DROP POLICY IF EXISTS rls_email_verification_codes_del ON "email_verification_codes";
DROP POLICY IF EXISTS rls_login_history_sel ON "login_history";
DROP POLICY IF EXISTS rls_login_history_ins ON "login_history";
DROP POLICY IF EXISTS rls_login_history_upd ON "login_history";
DROP POLICY IF EXISTS rls_login_history_del ON "login_history";
DROP POLICY IF EXISTS rls_password_resets_sel ON "password_resets";
DROP POLICY IF EXISTS rls_password_resets_ins ON "password_resets";
DROP POLICY IF EXISTS rls_password_resets_upd ON "password_resets";
DROP POLICY IF EXISTS rls_password_resets_del ON "password_resets";
DROP POLICY IF EXISTS rls_user_quotas_sel ON "user_quotas";
DROP POLICY IF EXISTS rls_user_quotas_ins ON "user_quotas";
DROP POLICY IF EXISTS rls_user_quotas_upd ON "user_quotas";
DROP POLICY IF EXISTS rls_user_quotas_del ON "user_quotas";
DROP POLICY IF EXISTS rls_used_approval_tokens_sel ON "used_approval_tokens";
DROP POLICY IF EXISTS rls_used_approval_tokens_ins ON "used_approval_tokens";
DROP POLICY IF EXISTS rls_used_approval_tokens_upd ON "used_approval_tokens";
DROP POLICY IF EXISTS rls_used_approval_tokens_del ON "used_approval_tokens";
DROP POLICY IF EXISTS rls_revoked_approval_tokens_sel ON "revoked_approval_tokens";
DROP POLICY IF EXISTS rls_revoked_approval_tokens_ins ON "revoked_approval_tokens";
DROP POLICY IF EXISTS rls_revoked_approval_tokens_upd ON "revoked_approval_tokens";
DROP POLICY IF EXISTS rls_revoked_approval_tokens_del ON "revoked_approval_tokens";
DROP POLICY IF EXISTS rls_job_events_sel ON "job_events";
DROP POLICY IF EXISTS rls_job_events_ins ON "job_events";
DROP POLICY IF EXISTS rls_job_events_upd ON "job_events";
DROP POLICY IF EXISTS rls_job_events_del ON "job_events";
DROP POLICY IF EXISTS rls_article_runs_sel ON "article_runs";
DROP POLICY IF EXISTS rls_article_runs_ins ON "article_runs";
DROP POLICY IF EXISTS rls_article_runs_upd ON "article_runs";
DROP POLICY IF EXISTS rls_article_runs_del ON "article_runs";
DROP POLICY IF EXISTS rls_batch_seo_cache_sel ON "batch_seo_cache";
DROP POLICY IF EXISTS rls_batch_seo_cache_ins ON "batch_seo_cache";
DROP POLICY IF EXISTS rls_batch_seo_cache_upd ON "batch_seo_cache";
DROP POLICY IF EXISTS rls_batch_seo_cache_del ON "batch_seo_cache";
DROP POLICY IF EXISTS rls_seo_logs_sel ON "seo_logs";
DROP POLICY IF EXISTS rls_seo_logs_ins ON "seo_logs";
DROP POLICY IF EXISTS rls_seo_logs_upd ON "seo_logs";
DROP POLICY IF EXISTS rls_seo_logs_del ON "seo_logs";
DROP POLICY IF EXISTS rls_social_post_variants_sel ON "social_post_variants";
DROP POLICY IF EXISTS rls_social_post_variants_ins ON "social_post_variants";
DROP POLICY IF EXISTS rls_social_post_variants_upd ON "social_post_variants";
DROP POLICY IF EXISTS rls_social_post_variants_del ON "social_post_variants";
DROP POLICY IF EXISTS rls_social_post_assets_sel ON "social_post_assets";
DROP POLICY IF EXISTS rls_social_post_assets_ins ON "social_post_assets";
DROP POLICY IF EXISTS rls_social_post_assets_upd ON "social_post_assets";
DROP POLICY IF EXISTS rls_social_post_assets_del ON "social_post_assets";
DROP POLICY IF EXISTS rls_social_post_jobs_sel ON "social_post_jobs";
DROP POLICY IF EXISTS rls_social_post_jobs_ins ON "social_post_jobs";
DROP POLICY IF EXISTS rls_social_post_jobs_upd ON "social_post_jobs";
DROP POLICY IF EXISTS rls_social_post_jobs_del ON "social_post_jobs";
DROP POLICY IF EXISTS rls_social_post_logs_sel ON "social_post_logs";
DROP POLICY IF EXISTS rls_social_post_logs_ins ON "social_post_logs";
DROP POLICY IF EXISTS rls_social_post_logs_upd ON "social_post_logs";
DROP POLICY IF EXISTS rls_social_post_logs_del ON "social_post_logs";
DROP POLICY IF EXISTS rls_error_logs_sel ON "error_logs";
DROP POLICY IF EXISTS rls_error_logs_ins ON "error_logs";
DROP POLICY IF EXISTS rls_error_logs_upd ON "error_logs";
DROP POLICY IF EXISTS rls_error_logs_del ON "error_logs";
DROP POLICY IF EXISTS rls_article_versions_sel ON "article_versions";
DROP POLICY IF EXISTS rls_article_versions_ins ON "article_versions";
DROP POLICY IF EXISTS rls_article_versions_upd ON "article_versions";
DROP POLICY IF EXISTS rls_article_versions_del ON "article_versions";
DROP POLICY IF EXISTS rls_coverage_nodes_sel ON "coverage_nodes";
DROP POLICY IF EXISTS rls_coverage_nodes_ins ON "coverage_nodes";
DROP POLICY IF EXISTS rls_coverage_nodes_upd ON "coverage_nodes";
DROP POLICY IF EXISTS rls_coverage_nodes_del ON "coverage_nodes";
DROP POLICY IF EXISTS rls_agent_optimization_logs_sel ON "agent_optimization_logs";
DROP POLICY IF EXISTS rls_agent_optimization_logs_ins ON "agent_optimization_logs";
DROP POLICY IF EXISTS rls_agent_optimization_logs_upd ON "agent_optimization_logs";
DROP POLICY IF EXISTS rls_agent_optimization_logs_del ON "agent_optimization_logs";
DROP POLICY IF EXISTS rls_persona_messaging_templates_sel ON "persona_messaging_templates";
DROP POLICY IF EXISTS rls_persona_messaging_templates_ins ON "persona_messaging_templates";
DROP POLICY IF EXISTS rls_persona_messaging_templates_upd ON "persona_messaging_templates";
DROP POLICY IF EXISTS rls_persona_messaging_templates_del ON "persona_messaging_templates";
DROP POLICY IF EXISTS rls_persona_behavioral_signals_sel ON "persona_behavioral_signals";
DROP POLICY IF EXISTS rls_persona_behavioral_signals_ins ON "persona_behavioral_signals";
DROP POLICY IF EXISTS rls_persona_behavioral_signals_upd ON "persona_behavioral_signals";
DROP POLICY IF EXISTS rls_persona_behavioral_signals_del ON "persona_behavioral_signals";
DROP POLICY IF EXISTS rls_fact_versions_sel ON "fact_versions";
DROP POLICY IF EXISTS rls_fact_versions_ins ON "fact_versions";
DROP POLICY IF EXISTS rls_fact_versions_upd ON "fact_versions";
DROP POLICY IF EXISTS rls_fact_versions_del ON "fact_versions";
DROP POLICY IF EXISTS rls_oauth_credentials_sel ON "oauth_credentials";
DROP POLICY IF EXISTS rls_oauth_credentials_ins ON "oauth_credentials";
DROP POLICY IF EXISTS rls_oauth_credentials_upd ON "oauth_credentials";
DROP POLICY IF EXISTS rls_oauth_credentials_del ON "oauth_credentials";
DROP POLICY IF EXISTS rls_publishing_callbacks_sel ON "publishing_callbacks";
DROP POLICY IF EXISTS rls_publishing_callbacks_ins ON "publishing_callbacks";
DROP POLICY IF EXISTS rls_publishing_callbacks_upd ON "publishing_callbacks";
DROP POLICY IF EXISTS rls_publishing_callbacks_del ON "publishing_callbacks";
DROP POLICY IF EXISTS rls_schedule_runs_sel ON "schedule_runs";
DROP POLICY IF EXISTS rls_schedule_runs_ins ON "schedule_runs";
DROP POLICY IF EXISTS rls_schedule_runs_upd ON "schedule_runs";
DROP POLICY IF EXISTS rls_schedule_runs_del ON "schedule_runs";
DROP POLICY IF EXISTS rls_pattern_dimension_stats_sel ON "pattern_dimension_stats";
DROP POLICY IF EXISTS rls_pattern_dimension_stats_ins ON "pattern_dimension_stats";
DROP POLICY IF EXISTS rls_pattern_dimension_stats_upd ON "pattern_dimension_stats";
DROP POLICY IF EXISTS rls_pattern_dimension_stats_del ON "pattern_dimension_stats";
DROP POLICY IF EXISTS rls_journey_steps_sel ON "journey_steps";
DROP POLICY IF EXISTS rls_journey_steps_ins ON "journey_steps";
DROP POLICY IF EXISTS rls_journey_steps_upd ON "journey_steps";
DROP POLICY IF EXISTS rls_journey_steps_del ON "journey_steps";
DROP POLICY IF EXISTS rls_daily_brief_deliveries_sel ON "daily_brief_deliveries";
DROP POLICY IF EXISTS rls_daily_brief_deliveries_ins ON "daily_brief_deliveries";
DROP POLICY IF EXISTS rls_daily_brief_deliveries_upd ON "daily_brief_deliveries";
DROP POLICY IF EXISTS rls_daily_brief_deliveries_del ON "daily_brief_deliveries";
DROP POLICY IF EXISTS rls_cost_telemetry_sel ON "cost_telemetry";
DROP POLICY IF EXISTS rls_cost_telemetry_ins ON "cost_telemetry";
DROP POLICY IF EXISTS rls_cost_telemetry_upd ON "cost_telemetry";
DROP POLICY IF EXISTS rls_cost_telemetry_del ON "cost_telemetry";
DROP POLICY IF EXISTS rls_credit_balances_sel ON "credit_balances";
DROP POLICY IF EXISTS rls_credit_balances_ins ON "credit_balances";
DROP POLICY IF EXISTS rls_credit_balances_upd ON "credit_balances";
DROP POLICY IF EXISTS rls_credit_balances_del ON "credit_balances";
DROP POLICY IF EXISTS rls_credit_ledger_sel ON "credit_ledger";
DROP POLICY IF EXISTS rls_credit_ledger_ins ON "credit_ledger";
DROP POLICY IF EXISTS rls_credit_ledger_upd ON "credit_ledger";
DROP POLICY IF EXISTS rls_credit_ledger_del ON "credit_ledger";
DROP POLICY IF EXISTS rls_spending_caps_sel ON "spending_caps";
DROP POLICY IF EXISTS rls_spending_caps_ins ON "spending_caps";
DROP POLICY IF EXISTS rls_spending_caps_upd ON "spending_caps";
DROP POLICY IF EXISTS rls_spending_caps_del ON "spending_caps";
DROP POLICY IF EXISTS rls_usage_events_sel ON "usage_events";
DROP POLICY IF EXISTS rls_usage_events_ins ON "usage_events";
DROP POLICY IF EXISTS rls_usage_events_upd ON "usage_events";
DROP POLICY IF EXISTS rls_usage_events_del ON "usage_events";
DROP POLICY IF EXISTS rls_publishing_connections_sel ON "publishing_connections";
DROP POLICY IF EXISTS rls_publishing_connections_ins ON "publishing_connections";
DROP POLICY IF EXISTS rls_publishing_connections_upd ON "publishing_connections";
DROP POLICY IF EXISTS rls_publishing_connections_del ON "publishing_connections";
DROP POLICY IF EXISTS rls_job_batches_sel ON "job_batches";
DROP POLICY IF EXISTS rls_job_batches_ins ON "job_batches";
DROP POLICY IF EXISTS rls_job_batches_upd ON "job_batches";
DROP POLICY IF EXISTS rls_job_batches_del ON "job_batches";
DROP POLICY IF EXISTS rls_article_assets_sel ON "article_assets";
DROP POLICY IF EXISTS rls_article_assets_ins ON "article_assets";
DROP POLICY IF EXISTS rls_article_assets_upd ON "article_assets";
DROP POLICY IF EXISTS rls_article_assets_del ON "article_assets";
DROP POLICY IF EXISTS rls_social_posts_sel ON "social_posts";
DROP POLICY IF EXISTS rls_social_posts_ins ON "social_posts";
DROP POLICY IF EXISTS rls_social_posts_upd ON "social_posts";
DROP POLICY IF EXISTS rls_social_posts_del ON "social_posts";
DROP POLICY IF EXISTS rls_content_clusters_sel ON "content_clusters";
DROP POLICY IF EXISTS rls_content_clusters_ins ON "content_clusters";
DROP POLICY IF EXISTS rls_content_clusters_upd ON "content_clusters";
DROP POLICY IF EXISTS rls_content_clusters_del ON "content_clusters";
DROP POLICY IF EXISTS rls_video_ideas_sel ON "video_ideas";
DROP POLICY IF EXISTS rls_video_ideas_ins ON "video_ideas";
DROP POLICY IF EXISTS rls_video_ideas_upd ON "video_ideas";
DROP POLICY IF EXISTS rls_video_ideas_del ON "video_ideas";
DROP POLICY IF EXISTS rls_learning_agents_sel ON "learning_agents";
DROP POLICY IF EXISTS rls_learning_agents_ins ON "learning_agents";
DROP POLICY IF EXISTS rls_learning_agents_upd ON "learning_agents";
DROP POLICY IF EXISTS rls_learning_agents_del ON "learning_agents";
DROP POLICY IF EXISTS rls_learning_patterns_sel ON "learning_patterns";
DROP POLICY IF EXISTS rls_learning_patterns_ins ON "learning_patterns";
DROP POLICY IF EXISTS rls_learning_patterns_upd ON "learning_patterns";
DROP POLICY IF EXISTS rls_learning_patterns_del ON "learning_patterns";
DROP POLICY IF EXISTS rls_content_performance_metrics_sel ON "content_performance_metrics";
DROP POLICY IF EXISTS rls_content_performance_metrics_ins ON "content_performance_metrics";
DROP POLICY IF EXISTS rls_content_performance_metrics_upd ON "content_performance_metrics";
DROP POLICY IF EXISTS rls_content_performance_metrics_del ON "content_performance_metrics";
DROP POLICY IF EXISTS rls_audience_personas_sel ON "audience_personas";
DROP POLICY IF EXISTS rls_audience_personas_ins ON "audience_personas";
DROP POLICY IF EXISTS rls_audience_personas_upd ON "audience_personas";
DROP POLICY IF EXISTS rls_audience_personas_del ON "audience_personas";
DROP POLICY IF EXISTS rls_facts_sel ON "facts";
DROP POLICY IF EXISTS rls_facts_ins ON "facts";
DROP POLICY IF EXISTS rls_facts_upd ON "facts";
DROP POLICY IF EXISTS rls_facts_del ON "facts";
DROP POLICY IF EXISTS rls_fact_claims_sel ON "fact_claims";
DROP POLICY IF EXISTS rls_fact_claims_ins ON "fact_claims";
DROP POLICY IF EXISTS rls_fact_claims_upd ON "fact_claims";
DROP POLICY IF EXISTS rls_fact_claims_del ON "fact_claims";
DROP POLICY IF EXISTS rls_content_audit_trails_sel ON "content_audit_trails";
DROP POLICY IF EXISTS rls_content_audit_trails_ins ON "content_audit_trails";
DROP POLICY IF EXISTS rls_content_audit_trails_upd ON "content_audit_trails";
DROP POLICY IF EXISTS rls_content_audit_trails_del ON "content_audit_trails";
DROP POLICY IF EXISTS rls_agent_execution_manifests_sel ON "agent_execution_manifests";
DROP POLICY IF EXISTS rls_agent_execution_manifests_ins ON "agent_execution_manifests";
DROP POLICY IF EXISTS rls_agent_execution_manifests_upd ON "agent_execution_manifests";
DROP POLICY IF EXISTS rls_agent_execution_manifests_del ON "agent_execution_manifests";
DROP POLICY IF EXISTS rls_publishing_jobs_sel ON "publishing_jobs";
DROP POLICY IF EXISTS rls_publishing_jobs_ins ON "publishing_jobs";
DROP POLICY IF EXISTS rls_publishing_jobs_upd ON "publishing_jobs";
DROP POLICY IF EXISTS rls_publishing_jobs_del ON "publishing_jobs";
DROP POLICY IF EXISTS rls_content_schedules_sel ON "content_schedules";
DROP POLICY IF EXISTS rls_content_schedules_ins ON "content_schedules";
DROP POLICY IF EXISTS rls_content_schedules_upd ON "content_schedules";
DROP POLICY IF EXISTS rls_content_schedules_del ON "content_schedules";
DROP POLICY IF EXISTS rls_site_pages_sel ON "site_pages";
DROP POLICY IF EXISTS rls_site_pages_ins ON "site_pages";
DROP POLICY IF EXISTS rls_site_pages_upd ON "site_pages";
DROP POLICY IF EXISTS rls_site_pages_del ON "site_pages";
DROP POLICY IF EXISTS rls_site_crawl_jobs_sel ON "site_crawl_jobs";
DROP POLICY IF EXISTS rls_site_crawl_jobs_ins ON "site_crawl_jobs";
DROP POLICY IF EXISTS rls_site_crawl_jobs_upd ON "site_crawl_jobs";
DROP POLICY IF EXISTS rls_site_crawl_jobs_del ON "site_crawl_jobs";
DROP POLICY IF EXISTS rls_ai_learning_ledger_sel ON "ai_learning_ledger";
DROP POLICY IF EXISTS rls_ai_learning_ledger_ins ON "ai_learning_ledger";
DROP POLICY IF EXISTS rls_ai_learning_ledger_upd ON "ai_learning_ledger";
DROP POLICY IF EXISTS rls_ai_learning_ledger_del ON "ai_learning_ledger";
DROP POLICY IF EXISTS rls_content_reviews_sel ON "content_reviews";
DROP POLICY IF EXISTS rls_content_reviews_ins ON "content_reviews";
DROP POLICY IF EXISTS rls_content_reviews_upd ON "content_reviews";
DROP POLICY IF EXISTS rls_content_reviews_del ON "content_reviews";
DROP POLICY IF EXISTS rls_content_feedback_sel ON "content_feedback";
DROP POLICY IF EXISTS rls_content_feedback_ins ON "content_feedback";
DROP POLICY IF EXISTS rls_content_feedback_upd ON "content_feedback";
DROP POLICY IF EXISTS rls_content_feedback_del ON "content_feedback";
DROP POLICY IF EXISTS rls_judge_recalibration_queue_sel ON "judge_recalibration_queue";
DROP POLICY IF EXISTS rls_judge_recalibration_queue_ins ON "judge_recalibration_queue";
DROP POLICY IF EXISTS rls_judge_recalibration_queue_upd ON "judge_recalibration_queue";
DROP POLICY IF EXISTS rls_judge_recalibration_queue_del ON "judge_recalibration_queue";
DROP POLICY IF EXISTS rls_content_events_sel ON "content_events";
DROP POLICY IF EXISTS rls_content_events_ins ON "content_events";
DROP POLICY IF EXISTS rls_content_events_upd ON "content_events";
DROP POLICY IF EXISTS rls_content_events_del ON "content_events";
DROP POLICY IF EXISTS rls_client_intelligence_sel ON "client_intelligence";
DROP POLICY IF EXISTS rls_client_intelligence_ins ON "client_intelligence";
DROP POLICY IF EXISTS rls_client_intelligence_upd ON "client_intelligence";
DROP POLICY IF EXISTS rls_client_intelligence_del ON "client_intelligence";
DROP POLICY IF EXISTS rls_decision_policies_sel ON "decision_policies";
DROP POLICY IF EXISTS rls_decision_policies_ins ON "decision_policies";
DROP POLICY IF EXISTS rls_decision_policies_upd ON "decision_policies";
DROP POLICY IF EXISTS rls_decision_policies_del ON "decision_policies";
DROP POLICY IF EXISTS rls_decision_arms_sel ON "decision_arms";
DROP POLICY IF EXISTS rls_decision_arms_ins ON "decision_arms";
DROP POLICY IF EXISTS rls_decision_arms_upd ON "decision_arms";
DROP POLICY IF EXISTS rls_decision_arms_del ON "decision_arms";
DROP POLICY IF EXISTS rls_holdout_assignments_sel ON "holdout_assignments";
DROP POLICY IF EXISTS rls_holdout_assignments_ins ON "holdout_assignments";
DROP POLICY IF EXISTS rls_holdout_assignments_upd ON "holdout_assignments";
DROP POLICY IF EXISTS rls_holdout_assignments_del ON "holdout_assignments";
DROP POLICY IF EXISTS rls_variant_arms_sel ON "variant_arms";
DROP POLICY IF EXISTS rls_variant_arms_ins ON "variant_arms";
DROP POLICY IF EXISTS rls_variant_arms_upd ON "variant_arms";
DROP POLICY IF EXISTS rls_variant_arms_del ON "variant_arms";
DROP POLICY IF EXISTS rls_client_brand_profiles_sel ON "client_brand_profiles";
DROP POLICY IF EXISTS rls_client_brand_profiles_ins ON "client_brand_profiles";
DROP POLICY IF EXISTS rls_client_brand_profiles_upd ON "client_brand_profiles";
DROP POLICY IF EXISTS rls_client_brand_profiles_del ON "client_brand_profiles";
DROP POLICY IF EXISTS rls_cohort_insights_sel ON "cohort_insights";
DROP POLICY IF EXISTS rls_cohort_insights_ins ON "cohort_insights";
DROP POLICY IF EXISTS rls_cohort_insights_upd ON "cohort_insights";
DROP POLICY IF EXISTS rls_cohort_insights_del ON "cohort_insights";
DROP POLICY IF EXISTS rls_journeys_sel ON "journeys";
DROP POLICY IF EXISTS rls_journeys_ins ON "journeys";
DROP POLICY IF EXISTS rls_journeys_upd ON "journeys";
DROP POLICY IF EXISTS rls_journeys_del ON "journeys";
DROP POLICY IF EXISTS rls_cadence_performance_sel ON "cadence_performance";
DROP POLICY IF EXISTS rls_cadence_performance_ins ON "cadence_performance";
DROP POLICY IF EXISTS rls_cadence_performance_upd ON "cadence_performance";
DROP POLICY IF EXISTS rls_cadence_performance_del ON "cadence_performance";
DROP POLICY IF EXISTS rls_citation_probes_sel ON "citation_probes";
DROP POLICY IF EXISTS rls_citation_probes_ins ON "citation_probes";
DROP POLICY IF EXISTS rls_citation_probes_upd ON "citation_probes";
DROP POLICY IF EXISTS rls_citation_probes_del ON "citation_probes";
DROP POLICY IF EXISTS rls_daily_briefs_sel ON "daily_briefs";
DROP POLICY IF EXISTS rls_daily_briefs_ins ON "daily_briefs";
DROP POLICY IF EXISTS rls_daily_briefs_upd ON "daily_briefs";
DROP POLICY IF EXISTS rls_daily_briefs_del ON "daily_briefs";

-- ---------------------------------------------------------------------------
-- 2. Disable + NO FORCE RLS on every table
-- ---------------------------------------------------------------------------
ALTER TABLE IF EXISTS "activity_logs" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "activity_logs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "agent_execution_manifests" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "agent_execution_manifests" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "agent_optimization_logs" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "agent_optimization_logs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "ai_learning_ledger" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "ai_learning_ledger" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "article_assets" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "article_assets" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "article_runs" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "article_runs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "article_versions" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "article_versions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "articles" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "articles" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "audience_personas" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "audience_personas" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "batch_seo_cache" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "batch_seo_cache" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "cadence_performance" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "cadence_performance" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "citation_probes" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "citation_probes" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "client_brand_profiles" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "client_brand_profiles" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "client_intelligence" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "client_intelligence" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "cohort_insights" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "cohort_insights" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "content_audit_trails" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "content_audit_trails" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "content_clusters" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "content_clusters" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "content_events" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "content_events" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "content_feedback" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "content_feedback" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "content_performance_metrics" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "content_performance_metrics" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "content_reviews" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "content_reviews" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "content_schedules" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "content_schedules" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "cost_telemetry" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "cost_telemetry" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "coverage_nodes" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "coverage_nodes" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "credit_balances" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "credit_balances" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "credit_ledger" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "credit_ledger" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "credit_menu_overrides" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "credit_menu_overrides" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "daily_brief_deliveries" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "daily_brief_deliveries" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "daily_brief_preferences" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "daily_brief_preferences" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "daily_briefs" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "daily_briefs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "decision_arms" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "decision_arms" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "decision_policies" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "decision_policies" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "email_verification_codes" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "email_verification_codes" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "error_logs" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "error_logs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "fact_claims" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "fact_claims" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "fact_versions" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "fact_versions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "facts" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "facts" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "holdout_assignments" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "holdout_assignments" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "job_batches" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "job_batches" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "job_events" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "job_events" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "journey_steps" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "journey_steps" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "journey_templates" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "journey_templates" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "journeys" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "journeys" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "judge_recalibration_queue" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "judge_recalibration_queue" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "learning_agents" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "learning_agents" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "learning_patterns" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "learning_patterns" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "local_authority_signals" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "local_authority_signals" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "locales" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "locales" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "login_history" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "login_history" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "maintenance_flags" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "maintenance_flags" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "notifications" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "notifications" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "oauth_credentials" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "oauth_credentials" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "password_resets" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "password_resets" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "pattern_dimension_stats" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "pattern_dimension_stats" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "persona_behavioral_signals" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "persona_behavioral_signals" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "persona_messaging_templates" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "persona_messaging_templates" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "publishing_callbacks" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "publishing_callbacks" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "publishing_connections" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "publishing_connections" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "publishing_jobs" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "publishing_jobs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "revoked_approval_tokens" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "revoked_approval_tokens" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "schedule_runs" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "schedule_runs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "seo_logs" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "seo_logs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "sessions" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "sessions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "site_crawl_jobs" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "site_crawl_jobs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "site_pages" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "site_pages" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "social_post_assets" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "social_post_assets" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "social_post_jobs" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "social_post_jobs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "social_post_logs" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "social_post_logs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "social_post_variants" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "social_post_variants" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "social_posts" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "social_posts" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "spending_caps" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "spending_caps" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "team_members" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "team_members" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "teams" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "teams" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "totp_secrets" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "totp_secrets" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "usage_events" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "usage_events" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "used_approval_tokens" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "used_approval_tokens" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "user_invites" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "user_invites" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "user_quotas" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "user_quotas" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "users" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "users" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "variant_arms" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "variant_arms" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "video_ideas" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "video_ideas" DISABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- 3. Revoke grants from citefi_tenant
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'citefi_tenant') THEN
    EXECUTE 'REVOKE ALL ON "job_batches" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "article_assets" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "social_posts" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "content_clusters" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "video_ideas" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "learning_agents" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "learning_patterns" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "content_performance_metrics" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "audience_personas" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "facts" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "fact_claims" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "content_audit_trails" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "agent_execution_manifests" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "publishing_jobs" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "content_schedules" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "site_pages" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "site_crawl_jobs" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "ai_learning_ledger" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "content_reviews" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "content_feedback" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "judge_recalibration_queue" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "content_events" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "client_intelligence" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "decision_policies" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "decision_arms" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "holdout_assignments" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "variant_arms" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "client_brand_profiles" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "cohort_insights" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "journeys" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "cadence_performance" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "citation_probes" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "daily_briefs" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "cost_telemetry" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "credit_balances" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "credit_ledger" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "spending_caps" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "usage_events" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "publishing_connections" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "job_events" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "article_runs" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "batch_seo_cache" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "seo_logs" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "social_post_variants" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "social_post_assets" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "social_post_jobs" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "social_post_logs" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "error_logs" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "article_versions" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "coverage_nodes" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "agent_optimization_logs" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "persona_messaging_templates" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "persona_behavioral_signals" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "fact_versions" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "oauth_credentials" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "publishing_callbacks" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "schedule_runs" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "pattern_dimension_stats" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "journey_steps" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "daily_brief_deliveries" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "sessions" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "totp_secrets" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "email_verification_codes" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "login_history" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "password_resets" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "user_quotas" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "used_approval_tokens" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "revoked_approval_tokens" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "articles" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "notifications" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "daily_brief_preferences" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "user_invites" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "activity_logs" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "credit_menu_overrides" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "teams" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "team_members" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "users" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "locales" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "local_authority_signals" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "journey_templates" FROM citefi_tenant';
    EXECUTE 'REVOKE ALL ON "maintenance_flags" FROM citefi_tenant';
  END IF;
END
$$;

-- ---------------------------------------------------------------------------
-- 4. Drop helper functions (indirect helpers first, then core)
-- ---------------------------------------------------------------------------
DROP FUNCTION IF EXISTS citefi_rls.job_events_parent_access(integer, integer);
DROP FUNCTION IF EXISTS citefi_rls.article_runs_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.batch_seo_cache_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.seo_logs_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.social_post_variants_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.social_post_assets_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.social_post_jobs_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.social_post_logs_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.error_logs_parent_access(integer, integer);
DROP FUNCTION IF EXISTS citefi_rls.article_versions_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.coverage_nodes_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.agent_optimization_logs_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.persona_messaging_templates_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.persona_behavioral_signals_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.fact_versions_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.oauth_credentials_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.publishing_callbacks_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.schedule_runs_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.pattern_dimension_stats_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.journey_steps_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.daily_brief_deliveries_parent_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.user_shares_current_team(integer);
DROP FUNCTION IF EXISTS citefi_rls.team_in_context_hierarchy(integer);
DROP FUNCTION IF EXISTS citefi_rls.guard_client_viewer_article_update();
DROP FUNCTION IF EXISTS citefi_rls.tenant_can_access(integer);
DROP FUNCTION IF EXISTS citefi_rls.worker_team_active(integer);
DROP FUNCTION IF EXISTS citefi_rls.client_viewer_membership_valid(integer);
DROP FUNCTION IF EXISTS citefi_rls.web_membership_valid(integer);
DROP FUNCTION IF EXISTS citefi_rls.is_platform_admin();
DROP FUNCTION IF EXISTS citefi_rls.is_client_viewer();
DROP FUNCTION IF EXISTS citefi_rls.member_role();
DROP FUNCTION IF EXISTS citefi_rls.actor_type();
DROP FUNCTION IF EXISTS citefi_rls.current_user_id();
DROP FUNCTION IF EXISTS citefi_rls.current_team_id();

-- ---------------------------------------------------------------------------
-- 5. Drop helper schema
-- ---------------------------------------------------------------------------
DROP SCHEMA IF EXISTS citefi_rls CASCADE;

-- ---------------------------------------------------------------------------
-- 6. Drop the citefi_tenant role (grants/ownership already removed)
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'citefi_tenant') THEN
    EXECUTE format('REVOKE citefi_tenant FROM %I', current_user);
    DROP ROLE IF EXISTS citefi_tenant;
  END IF;
EXCEPTION WHEN OTHERS THEN
  -- If other objects still depend on the role in a shared cluster, leave it.
  RAISE NOTICE 'Could not drop role citefi_tenant: %', SQLERRM;
END
$$;

COMMIT;

-- ============================================================================
-- End of rollback 0014_tenant_rls_rollback.sql
-- ============================================================================
